[package]
name = "evergarden-font-manager"
version = "0.1.0"
description = "A modern, local font manager for creative professionals."
authors = ["Manju Madhav V A <manjumadhav.va@gmail.com>"]
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "evergarden_font_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

rusqlite = { version = "0.32", features = ["bundled"] }

ttf-parser = "0.24"

sha2 = "0.10"
hex = "0.4"

notify = "7"

reqwest = { version = "0.12", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }

once_cell = "1"

dirs = "5"
percent-encoding = "2"

[features]
# This feature is used for production builds or when a dev server is not specified.
# It enables the `devtools` feature of Tauri.
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
